levels:
  Starter:
    cost: 6
    increment: 2
    commodity: Seeds
    max: 6
    rewards:
     - 0 Seeds
     - 10 Wheat
     - 5 Bread
     - 5 BeetrootSeeds
     - 33 Wheat
     - 16 Carrot
  TorchBearer:
    cost: 32
    increment: 10
    commodity: Torch
    max: 3
    rewards:
     - 5 Glowstone
     - 9 CookedChicken
     - 15 IronOre
  Miner:
    cost: 24
    increment: 12
    commodity: Coal
    max: 4
    rewards:
     - 1 StonePickaxeU2
     - 1 StonePickaxeE2
     - 1 IronPickaxe
     - 16 TNT
  GoldDigger:
    cost: 16
    increment: 4
    commodity: Gold
    max: 4
    rewards:
    - 1 IronBoots
    - 1 IronHelmet
    - 1 GoldChestplate
    - 1 GoldLeggings
  Redstoner:
    cost: 6
    increment: 3
    commodity: RedstoneBlock
    max: 4
    rewards:
     - 50 RedstoneTorch
     - 64 Rails
     - 30 PowerRail
     - 20 Dispenser
  Adept:
    cost: 7
    increment: 4
    commodity: GoldIngot
    max: 5
    rewards:
    - 9 Obsidian
    - 10 Bookshelf
    - 1 IronChestplate
    - 1 Bow
    - 1 DiamondPickaxe
  Expert:
    cost: 10
    increment: 6
    commodity: GoldIngot
    max: 4
    rewards:
    - 8 Diamond
    - 8 Chest
    - 10 obsidian
    - 1 IronLeggings
  Master:
    cost: 20
    increment: 5
    commodity: GoldIngot
    max: 4
    rewards:
    - 1 DiamondHelmet
    - 1 DiamondBoots
    - 1 DiamondLeggings
    - 1 DiamondChestplate
  Lord:
    cost: 40
    increment: 4
    commodity: GoldIngot
    max: 4
    rewards:
    - 64 Wood
    - 64 XpBottle
    - 1 Shield
    - 15 emerald
  President:
    cost: 3
    increment: 1
    commodity: EmeraldBlock
    max: 5
    rewards:
    - 1 PresidentHead
    - 1 BlackShoes
    - 1 BlackTrousers    
    - 1 BlackSuit
    - 1 Microphone
  God:
    cost: 8
    increment: 2
    commodity: EmeraldBlock
    max: 5
    rewards:
    - 1 GodlyPickaxe
    - 1 GodlyAxe
    - 1 GodlyShovel
    - 1 GodlyHoe
    - 1 GodlyShears
  Titan:
    cost: 20
    increment: 4
    commodity: EmeraldBlock
    max: 5
    rewards:
    - 1 TitanHelmet
    - 1 TitanBoots
    - 1 TitanLeggings
    - 1 TitanChestplate
    - 1 TheUltimateItem
  Overlord:
    cost: 6
    increment: 1
    commodity: Bedrock
    max: 100

commodities:
  # currencies
  Seeds:
    material: SEEDS
    sell: 2.5
    buy: 3.0
    currency: true
  Torch:
    material: TORCH
    sell: 4.5
    buy: 5.0
    currency: true
  Coal:
    material: COAL
    sell: 14.0
    buy: 15.0
    currency: true
  Gold:
    material: GOLD_NUGGET
    sell: 10.0
    buy: 11.0
    currency: true
  RedstoneBlock:
    material: REDSTONE_BLOCK
    sell: 50.0
    buy: 60.0
    currency: true
  GoldIngot:
    material: GOLD_INGOT
    sell: 90.0
    buy: 100.0
    currency: true
  GoldBlock:
    material: GOLD_BLOCK
    sell: 800.0
    buy: 900.0
    currency: true
  Emerald:
    material: EMERALD
    sell: 200
    buy: 220
    rarity: 0.5
    currency: true
  EmeraldBlock:
    material: EMERALD_BLOCK
    sell: 1800
    buy: 2000
    rarity: 0.5
    currency: true

  # buy-sell
  Wheat:
    material: WHEAT
    sell: 2.5
    buy: 3.0
  Carrot:
    material: CARROT_ITEM
    sell: 1.5
    buy: 2.0
  BeetrootSeeds:
    material: BEETROOT_SEEDS
    sell: 1.0
    buy: 1.2
  Beetroot:
    material: BEETROOT
    sell: 0.5
    buy: 0.7
  Sugar:
    material: SUGAR
    sell: 4.5
    buy: 5.0
    rarity: 0.5
  Bone:
    material: BONE
    sell: 8
    buy: 10
  Apple:
    material: APPLE
    sell: 7.0
    buy: 10.0
    rarity: 0.5
    max: 32
  Glowstone:
    material: GLOWSTONE
    sell: 25.0
    buy: 30.0
  IronOre:
    material: IRON_ORE
    sell: 20.0
    buy: 26.0
  IronIngot:
    material: IRON_INGOT
    sell: 30.0
    buy: 40.0
  Brick:
    material: BRICK
    sell: 25.0
    buy: 30.0
  XP:
    material: EXP_BOTTLE
    sell: 35.0
    buy: 40.0
    rarity: 0.5
  Book:
    material: BOOK
    sell: 35.0
    buy: 45.0
    rarity: 0.5

  # sell items
  Cobblestone:
    material: COBBLESTONE
    sell: 0.8
  Stone:
    material: STONE
    data: 0
    sell: 1.5
  Fence:
    material: FENCE
    sell: 1.5
    rarity: 0.5
  Granite:
    material: STONE
    data: 1
    sell: 1.5
    rarity: 0.5
  Diorite:
    material: STONE
    data: 3
    sell: 1.5
    rarity: 0.5
  Andesite:
    material: STONE
    data: 5
    sell: 1.5
    rarity: 0.5
  PolishGranite:
    material: STONE
    data: 2
    sell: 2
  PolishDiorite:
    material: STONE
    data: 4
    sell: 2
  PolishAndesite:
    material: STONE
    data: 6
    sell: 2
  Fence:
    material: FENCE
    sell: 1.5
    rarity: 0.5
  RottenFlesh:
    material: ROTTEN_FLESH
    sell: 10
  EnderPearl:
    material: ENDER_PEARL
    sell: 30
  Sand:
    material: SAND
    sell: 1.0
  Sandstone:
    material: SANDSTONE
    sell: 4.0
  SmoothSand:
    material: SANDSTONE
    data: 2
    sell: 6.0
  Glass:
    material: GLASS
    sell: 3.0
  Wood:
    material: WOOD
    sell: 0.5
  Gravel:
    material: GRAVEL
    sell: 0.5
  BakedPotato:
    material: BAKED_POTATO
    sell: 15
  Obsidian:
    material: OBSIDIAN
    sell: 50
    buy: 130
    max: 16

  # buy items
  Bread:
    material: BREAD
    buy: 9.0
  CookedChicken:
    material: COOKED_CHICKEN
    buy: 10.0
  Potato:
    material: POTATO_ITEM
    buy: 20
    max: 32
  Fish:
    material: RAW_FISH
    buy: 7.0
    max: 32
  Chicken:
    material: RAW_CHICKEN
    buy: 10.0
    max: 32
  Rails:
    material: RAILS
    buy: 22
    rarity: 0.3
  Compass:
    material: COMPASS
    buy: 22
    rarity: 0.1
    max: 1
  PowerRail:
    material: POWERED_RAIL
    buy: 65
    rarity: 0.2
  Fireworks:
    material: FIREWORK
    buy: 10
    rarity: 0.2
  Bedrock:
    material: BEDROCK
    buy: 10000
    rarity: 0.5
  TNT:
    material: TNT
    buy: 100.0
  RedstoneTorch:
    material: REDSTONE_TORCH_ON
    buy: 4.0
  Dispenser:
    material: DISPENSER
    buy: 20.0
  StonePickaxeU2:
    material: STONE_PICKAXE
    unbreaking: 2
  StonePickaxeE2:
    material: STONE_PICKAXE
    efficiency: 2
  IronPickaxe:
    material: IRON_PICKAXE
    efficiency: 2
  IronBoots:
    material: IRON_BOOTS
  IronHelmet:
    material: IRON_HELMET
  IronChestplate:
    material: IRON_CHESTPLATE
    protection: 3
    unbreaking: 1
  GoldChestplate:
    material: GOLD_CHESTPLATE
    unbreaking: 4
    protection: 2
  DiamondPickaxe:
    material: DIAMOND_PICKAXE
    efficiency: 2
  Bow:
    material: BOW
    power: 1
    flame: 1
  IronLeggings:
    material: IRON_CHESTPLATE
    protection: 3
  DiamondHelmet:
    material: DIAMOND_HELMET
    protection: 1
  DiamondBoots:
    material: DIAMOND_BOOTS
    protection: 1
  DiamondLeggings:
    material: DIAMOND_LEGGINGS
    protection: 1
  DiamondChestplate:
    material: DIAMOND_CHESTPLATE
    protection: 1
  Wood:
    material: LOG
    sell: 6.0
    buy: 8.0
  XPBottle:
    material: EXP_BOTTLE
  BlackSuit:
    material: LEATHER_CHESTPLATE
    protection: 10
    unbreaking: 10
  PresidentHead:
    material: SKULL_ITEM
    protection: 15
  BlackTrousers:
    material: LEATHER_LEGGINGS
    protection: 10
    unbreaking: 10
  BlackShoes:
    material: LEATHER_BOOTS
    protection: 10
    unbreaking: 10
  Microphone:
    material: LEVER
    sharpness: 10
    fire_aspect: 1
  IronChestplateP3:
    material: IRON_CHESTPLATE
    protection: 3
  GoldLeggings:
    material: GOLD_LEGGINGS
    unbreaking: 4
    protection: 2
  TheUltimateItem:
    material: DEAD_BUSH
    sharpness: 10
    fire_aspect: 10
    smite: 10
    bane_of_arthropods: 10
    knockback: 3
    fire_aspect: 10
    looting: 10
    efficiency: 10
    unbreaking: 10
  TitanHelmet:
    material: DIAMOND_HELMET
    protection: 15
    unbreaking: 15
    aqua_affinity: 5
  TitanChestplate:
    material: DIAMOND_CHESTPLATE
    protection: 15
    unbreaking: 15
  TitanLeggings:
    material: DIAMOND_LEGGINGS
    protection: 15
    unbreaking: 15
  TitanBoots:
    material: DIAMOND_BOOTS
    protection: 15
    unbreaking: 15
    depth_strider: 5
  GodlyShears:
    material: SHEARS
    unbreaking: 7
    fortune: 5
    efficiency: 10
  GodlyAxe:
    material: DIAMOND_AXE
    unbreaking: 7
    fortune: 5
    efficiency: 10
  GodlyHoe:
    material: DIAMOND_HOE
    unbreaking: 7
    fortune: 5
    efficiency: 10
  GodlyShovel:
    material: DIAMOND_SPADE
    unbreaking: 7
    fortune: 5
    efficiency: 10
  GodlyPickaxe:
    material: DIAMOND_PICKAXE
    unbreaking: 7
    fortune: 5
  Emerald:
    material: EMERALD
    buy: 350
    sell: 400
    rarity: 0.1
  Bookshelf:
    material: BOOKSHELF
    buy: 90
  Diamond:
    material: DIAMOND
  Chest:
    material: CHEST
    buy: 10
  Shield:
    material: SHIELD
    unbreaking: 1

## enchantments ##
# protection: 1 - 4
# fire_protection: 1 - 4
# feather_falling: 1 - 4
# blast_protection: 1 - 4
# projectile_protection: 1 - 4
# respiration: 1 - 3
# aqua_affinity: 1 - 1
# thorns: 1 - 3
# depth_strider: 1 - 3
# frost_walker: 1 - 2
# sharpness: 1 - 5
# smite: 1 - 5
# bane_of_arthropods: 1 - 5
# knockback: 1 - 2
# fire_aspect: 1 - 2
# looting: 1 - 3
# efficiency: 1 - 5
# silk_touch: 1 - 1
# unbreaking: 1 - 3
# fortune: 1 - 3
# power: 1 - 5
# punch: 1 - 2
# flame: 1 - 1
# infinity: 1 - 1
# luck_of_the_sea: 1 - 3
# lure: 1 - 3
# mending: 1 - 1
