levels:
  Starter:
    cost: 6
    increment: 2
    commodity: Seeds
    max: 6
    rewards:
     - 0 Seeds
     - 10 Wheat
     - 5 Bread
     - 5 BeetrootSeeds
     - 33 Wheat
     - 16 Carrot
  TorchBearer:
    cost: 32
    increment: 10
    commodity: Torch
    max: 3
    rewards:
     - 5 Glowstone
     - 9 CookedChicken
     - 15 IronOre
#1.1 stone pickaxe with unbreaking 1
#2.1 stone pickaxe efficiency 1
#3.1 iron pick with efficiency 2
#4.16 TNT
  Miner:
    cost: 24
    increment: 12
    commodity: Coal
    max: 4
    rewards:
     - 1 StonePickaxeU2
     - 1 StonePickaxeE2
     - 1 IronPickaxeE2
     - 16 TNT
#1.iron boots unbreaking 2
#2.iron helmet protection 1
#3.gold chestplate unbreaking 4 protection 2
#4.gold leggings unbreaking 5 protection 4
  GoldDigger:
    cost: 16
    increment: 4
    commodity: Gold
    max: 4
    rewards:
    - 1 IronBootsU2
    - 1 IronHelmetP1
    - 1 GoldChestplateU4P2
    - 1 GoldLeggingsU5P4
  Redstoner:
    cost: 6
    increment: 3
    commodity: RedstoneBlock
    max: 4
    rewards:
     - 50 RedstoneTorch
     - 64 Rails
     - 30 PowerRail
     - 20 Dispenser
#1.9 Obsidian
#2.10 Bookshelves
#3.Iron Chestplate protection 3 unbreaking 1
#4.Bow power 1, 30 arrows
#5.Diamond Pickaxe Efficiency 2
  Adept:
    cost: 7
    increment: 4
    commodity: GoldIngot
    max: 5
    rewards:
    - 9 Obsidian
    - 10 Bookshelf
    - 1 IronChestplateP3U1
    - 1.BowP1
    - 1.DiamondPickaxeE2
#1.5 Diamonds
#2.8 Chests
#3.10 Obsidian
#4.iron leggings protection 3
  Expert:
    cost: 10
    increment: 6
    commodity: GoldIngot
    max: 4
    rewards:
    - 5 Diamond
    - 8 Chest
    - 10 obsidian
    - 1 IronLeggingsP3
#1.
#2.
#3.
#4.
  Master:
    cost: 20
    increment: 5
    commodity: GoldIngot
    max: 4
    rewards
    - 1 DiamondHelmetP1
    - 1 DiamondBootsP1
    - 1 DiamondLeggingsP1
    - 1 DiamondChestplateP1
  Lord:
    cost: 40
    increment: 4
    commodity: GoldIngot
    max: 4
    rewards:
    - 64 Wood
    - 64 Xp Bottle
    - 
    - /fly
#1.Steve Head protection 15
#2.Black Leather Boots protection 10 unbreaking 10
#3.Black Leather Leggings protection 10 unbreaking 10
#4.Black Leather Tunic protection 10 unbreaking 10
#5.Lever thats called a microphone Sharpness 10 Fire Aspect 1
  President:
    cost: 3
    increment: 1
    commodity: EmeraldBlock
    max: 5
#1.
#2.
#3.
#4.
#5.
  God:
    cost: 8
    increment: 2
    commodity: EmeraldBlock
    max: 5
#1.
#2.
#3.
#4.
#5.
#6.gamemode 1
  Titan:
    cost: 20
    increment: 4
    commodity: EmeraldBlock
    max: 6
  Overlord:
    cost: 6
    increment: 1
    commodity: Bedrock
    max: 100

commodities:
  # currencies
  Seeds:
    material: SEEDS
    sell: 2.5
    buy: 3.0
    currency: true
  Torch:
    material: TORCH
    sell: 4.5
    buy: 5.0
    currency: true
  Coal:
    material: COAL
    sell: 14.0
    buy: 15.0
    currency: true
  Gold:
    material: GOLD_NUGGET
    sell: 10.0
    buy: 11.0
    currency: true
  RedstoneBlock:
    material: REDSTONE_BLOCK
    sell: 50.0
    buy: 60.0
    currency: true
  GoldIngot:
    material: GOLD_INGOT
    sell: 90.0
    buy: 100.0
    currency: true
  GoldBlock:
    material: GOLD_BLOCK
    sell: 800.0
    buy: 900.0
    currency: true
  Emerald:
    material: EMERALD
    sell: 200
    buy: 220
    rarity: 0.5
    currency: true
  EmeraldBlock:
    material: EMERALD_BLOCK
    sell: 1800
    buy: 2000
    rarity: 0.5
    currency: true

  # buy-sell
  Wheat:
    material: WHEAT
    sell: 2.5
    buy: 3.0
  Carrot:
    material: CARROT_ITEM
    sell: 1.5
    buy: 2.0
  BeetrootSeeds:
    material: BEETROOT_SEEDS
    sell: 1.0
    buy: 1.2
  Beetroot:
    material: BEETROOT
    sell: 0.5
    buy: 0.7
  Sugar:
    material: SUGAR
    sell: 4.5
    buy: 5.0
    rarity: 0.5
  Bone:
    material: BONE
    sell: 8
    buy: 10
  Apple:
    material: APPLE
    sell: 7.0
    buy: 10.0
    rarity: 0.5
    max: 32
  Glowstone:
    material: GLOWSTONE
    sell: 25.0
    buy: 30.0
  IronOre:
    material: IRON_ORE
    sell: 20.0
    buy: 26.0
  IronIngot:
    material: IRON_INGOT
    sell: 30.0
    buy: 40.0
  Brick:
    material: BRICK
    sell: 25.0
    buy: 30.0
  XP:
    material: EXP_BOTTLE
    sell: 35.0
    buy: 40.0
    rarity: 0.5
  Book:
    material: BOOK
    sell: 35.0
    buy: 45.0
    rarity: 0.5

  # sell items
  Cobblestone:
    material: COBBLESTONE
    sell: 0.8
  Stone:
    material: STONE
    data: 0
    sell: 1.5
  Fence:
    material: FENCE
    sell: 1.5
    rarity: 0.5
  Granite:
    material: STONE
    data: 1
    sell: 1.5
    rarity: 0.5
  Diorite:
    material: STONE
    data: 3
    sell: 1.5
    rarity: 0.5
  Andesite:
    material: STONE
    data: 5
    sell: 1.5
    rarity: 0.5
  PolishGranite:
    material: STONE
    data: 2
    sell: 2
  PolishDiorite:
    material: STONE
    data: 4
    sell: 2
  PolishAndesite:
    material: STONE
    data: 6
    sell: 2
  Fence:
    material: FENCE
    sell: 1.5
    rarity: 0.5
  RottenFlesh:
    material: ROTTEN_FLESH
    sell: 10
  EnderPearl:
    material: ENDER_PEARL
    sell: 30
  Sand:
    material: SAND
    sell: 1.0
  Sandstone:
    material: SANDSTONE
    sell: 4.0
  SmoothSand:
    material: SANDSTONE
    data: 2
    sell: 6.0
  Glass:
    material: GLASS
    sell: 3.0
  Wood:
    material: WOOD
    sell: 0.5
  Gravel:
    material: GRAVEL
    sell: 0.5
  BakedPotato:
    material: BAKED_POTATO
    sell: 15
  Obsidian:
    material: OBSIDIAN
    sell: 50
    buy: 130
    max: 16

  # buy items
  Bread:
    material: BREAD
    buy: 9.0
  CookedChicken:
    material: COOKED_CHICKEN
    buy: 10.0
  Potato:
    material: POTATO_ITEM
    buy: 20
    max: 32
  Fish:
    material: RAW_FISH
    buy: 7.0
    max: 32
  Chicken:
    material: RAW_CHICKEN
    buy: 10.0
    max: 32
  Rails:
    material: RAILS
    buy: 22
    rarity: 0.3
  Compass:
    material: COMPASS
    buy: 22
    rarity: 0.1
    max: 1
  PowerRail:
    material: POWERED_RAIL
    buy: 65
    rarity: 0.2
  Fireworks:
    material: FIREWORK
    buy: 10
    rarity: 0.2
  Bedrock:
    material: BEDROCK
    buy: 10000
    rarity: 0.5
  TNT:
    material: TNT
    buy: 100.0
  RedstoneTorch:
    material: REDSTONE_TORCH
    buy: 4.0
  Dispenser:
    material: DISPENSER
    buy: 20.0
  StonePickaxeU2:
    material: STONE_PICKAXE
    unbreaking: 2
  StonePickaxeE2:
    material: STONE_PICKAXE
    efficiency: 2
  IronPickaxeE2:
    material: IRON_PICKAXE
    efficiency: 2
  IronBootsU2
    material:IRON_BOOTS
  IronHelmetP1
    material:IRON_HELMET
  IronChestplateP3U1
    material:IRON_CHESTPLATE
    Protection:3
    Unbreaking:1
  GoldChestplateU4P2
    material:GOLD_CHESTPLATE
    Unbreaking:4
    Protection:2
  DiamondPickaxeE2
    material:DIAMOND_PICKAXE
    Efficiency:2
  BowP1
    material:BOW
    Power:1
  IronLeggingsP3
    material:IRON_CHESTPLATE
    Protection:3
  DiamondHelmetP1
    material:DIAMONDHELMET
    Protection:1
  DiamondBootsP1
    material:DIAMONDBOOTS
    Protection:1
  DiamondLeggingsP1
    material:DIAMONDLEGGINGS
    Protection:1
  DiamondChestplateP1
    material:DIAMONDCHESTPLATE
    Protection:1
  Wood
    material:LOG
    sell:6.0
    buy:8.0
  XPBottle
    material:EXPERIENCEBOTTLE
